### ISSUE TITLE
Unable to execute any command on ftp client side

### ISSUE THREAD

**Issue by shoaibi** [chmouel/ftp-cloudfs#12]
I have 2 servers.
Server A: Runs ftp-cloudfs on port 21[config shown below]
Server B: client box, uploads files to Server A's FTP server

When i try to execute any command on the FTP client at Server B, i get:
501 Can't connect to a foreign address.
ftp: bind: Address already in use

This doesn't happen on the ftp client that runs on Server A.

and if its any use, both Server A and Server B on AWS, Server A being in us-east and Server B being in us-west. The masquerade ip below in the ftpcloudfs config is the elastic ip of Server A.

ftp-cloudfs config on server A:

```
# ftpcloudfs example configuration file
[ftpcloudfs]

# FTP banner (%v version, %f ftp handler version)
banner = Rackspace Cloud Files %v using pyftpdlib %f ready.

# Port to bind.
port = 21

# Address to bind.
bind-address = 0.0.0.0

# Number of workers to use.
# The number of workers depends on the number of available
# cores and the expected load.
workers = 1

# Auth URL for alternate providers (eg OpenStack)
auth-url = https://lon.auth.api.rackspacecloud.com/v1.0
#auth-url = https://auth.api.rackspacecloud.com/v1.0

# Connect via Rackspace ServiceNet network.
# service-net = no

# Be verbose on logging.
verbose = no

# Enable logging to the system logger.
syslog = yes

# Log file location.
log-file = 

# Pid file location when in daemon mode.
pid-file = /var/run/ftpcloudfs.pid

# UID to drop priviliges when in daemon mode.
uid = 65534

# GID to drop priviliges when in daemon mode.
gid = 65534

# Masquerade IP address in case your server is behind a firewall or NATed.
# assume Server A is behind 11.11.11.11
masquerade-firewall = 11.11.11.11

# EOF
```

**Comment by shoaibi** [comment]
In logs it says:

```
Sep 21 20:53:16 ip-10-243-2-111 ftpcloudfs[25920]: [userhere]@external.ip.of.server.b:35618 Rejected data connection to foreign address internal.ip.of.server.b:35887.
```

Even tried with client using passive (as you see from above log that the FTP server is trying to connect to internal IP of server b on port 35887) but there isn't a config option of ftpcloudfs that lets configure range for passive ports.

```
$ ftp -dp servera.com
Connected to servera.compute-1.amazonaws.com.
220 Rackspace Cloud Files 0.9 using pyftpdlib 0.6.0 ready.
ftp: setsockopt: Bad file descriptor
Name (servera.com:root): userhere
---> USER userhere
331 Username ok, send password.
Password:
---> PASS XXXX
230 Welcome userhere
---> SYST
215 UNIX Type: L8
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
---> PASV
227 Entering passive mode
ftp: connect: Connection timed out

```

**Comment by ncw** [comment]
Are there firewalls between A and B?  Because FTP mixes layer 3 and layer 7 by sending ip addresses and port numbers over TCP it needs a firewall which understands FTP to work.  You can work around this by allowing the passive port range through the firewall (1024 to 65535).  If you need a narrower range than this then we'd need to make a config parameter for _passive_ports_ in pyftpdlib - patches gratefully received!

The other thing you could try is setting the _bind-address_ to the actual real IP that server A connects out to the internet on.  If it is behind a NAT firewall then you use the IP address that it is NATted to.

**Comment by reidrac** [comment]
I'm closing this because it looks like a network issue.

Please don't hesitate to open it again if you can update it with more information!
