### ISSUE TITLE
username and password when using Openstack

### ISSUE THREAD

**Issue by gernotger** [chmouel/ftp-cloudfs#16]
when using curl I use as username: myaccname:myusername
and as a password: mypassword

like this:
curl -k -v -H 'X-Storage-User: myaccname:myusername' -H 'X-Storage-Pass: mypassword' http://127.0.0.1:8080/auth/v1.0

I dont know how to use these with ftp-cloudfs.

ftp://myaccname:myusername:mypassword@127.0.0.1:2021 
this could not be right.

Please give an example and note it in your readme

thank you

best regards

**Comment by chmouel** [comment]
You would use "myaccname:myusername" as username and mypassword and as
password in your FTP software, what's wrong with it?

**Comment by reidrac** [comment]
I guess the problem is with the FTP URI definition, that doesn't play well with colons, but that doesn't mean any FTP client will have problems with that.

I don't know if the colon can be codified in the URI in the same way the @ can be replaced by %40.

I'd say this is not a bug :)

**Comment by c35sys** [comment]
I had the same issue.

Juan is right about the codified colon, you can use "%3a" instead ":" .

I tried with ftp and lftp using the following solution:

# With ftp command line (v0.17)

ftp localhost
Name: account%3auser
Password: yourpass
ftp> passive
ftp> ls

# With lftp command line (v4.3.1)

lftp account%3auser:yourpass@localhost
lftp> ls

# With lftp command line (v4.3.1) using sftp (sftpcloudfs)

lftp sftp://account%3auser:yourpass@localhost:115
lftp> ls

**Comment by reidrac** [comment]
Thanks Christophe!

I've added this to a FAQ wiki page: https://github.com/chmouel/ftp-cloudfs/wiki/FAQ
