### ISSUE TITLE
Connecting using filezilla

### ISSUE THREAD

**Issue by Talon876** [chmouel/ftp-cloudfs#25]
Running ftpcloudfs on another computer on my lan (running ubuntu 12.04)
I started the program with: ftpcloudfs -s
There wasn't any output, not sure if that's expected. 

Now I'm trying to connect with filezilla on my windows 7 machine. I put 192.168.245.129 (ip of the ubuntu machine) in my host field, my rackspace username, my rackspace password, and 2021 for the port.

I'm getting this:

Status: Connecting to 192.168.245.129:2021...
Status: Connection attempt failed with "ECONNREFUSED - Connection refused by server".
Error:  Could not connect to server
Status: Waiting to retry...
Status: Connecting to 192.168.245.129:2021...
Status: Connection attempt failed with "ECONNREFUSED - Connection refused by server".
Error:  Could not connect to server

I'm assuming it's something I'm done and not an actual bug. I'm guessing it has something to do with how I'm giving it my credentials but I'm not sure what else I could try

**Comment by reidrac** [comment]
By default the service listens on 127.0.0.1. That means that you can't connect to the service from a different machine. You can try running ftpcloudfs with -b 0.0.0.0 so it listens in all your network interfaces.

You can add the flags -vf to get output on the console (you can end the service with CTRL + c) and check if there's any log related to your connection attempt. This is useful when troubleshooting and you can remove the flags once you have verified it's working.

I recommend you to read the README.rst file :)
