### ISSUE TITLE
keystone compatibility

### ISSUE THREAD

**Issue by mfortin** [chmouel/ftp-cloudfs#29]
ftpcloudfs only works with swauth.

Would it be possible to add compatibility for keystone as well, as it seems to be the way OpenStack is heading ?

Thanks!

**Comment by reidrac** [comment]
ftpcloudfs relies on python-cloudfiles (see https://github.com/rackspace/python-cloudfiles), a python module to support RackSpace Cloud Files API. CF API is compatible with OpenStack Object Storage, but it only supports auth v1.0 as described in:

http://docs.openstack.org/api/openstack-object-storage/1.0/content/authentication-object-dev-guide.html

I don't think python-cloudfiles will support OpenStack Identity Service (aka Keystone), but the authentication part is easy to extend to support other authentication systems.

To be honest with you I don't use Swift with Keystone and I'm not very familiar with the API, but I guess we could add support at some point after Folsom release when all the new stuff introduced in Essex is stable.

**Comment by reidrac** [comment]
I've created a branch that adds auth 2.0 support using python-keystoneclient.

https://github.com/chmouel/ftp-cloudfs/tree/auth-2.0

Any help testing it would be greatly appreciated!

**Comment by reidrac** [comment]
Did you have any chance to test the keystone auth? :)

**Comment by schuermannkl** [comment]
Hi, I tried using the keystone-auth.
I get a correct JSON-Response from the keystone server, but it can't find the right endpoint. If I comment auth the lines 97-107 and put in a hard coded endpoint like

return ("http://10.200.21.1:80/v1/AUTH_78e3bf1d680842518c95f5d19bb559fe", None, "3ffb6fb237294a558b2b1fe68c691122")

everything works fine and I can use my ftp-program.

**Comment by reidrac** [comment]
So you get an "End point not found error".

I would appreciate if you run the server with -v -l ftp.log flags and send me the ftp.log file (check that it doesn't include any confidential data; you can change that with ****).

EDIT: did you specify a region name? that's the only part that may affect the endpoint call.

**Comment by reidrac** [comment]
Thanks for you mail with the log, you actually found a stupid bug.

I've committed a fix in 5e5199e33be4a474335998443a821a5752f6ace4 ; can you try it to see if it fixes your problem?

Thanks for your help!

**Comment by schuermannkl** [comment]
That fixed it. It's working very well now.

Thank you for your quick reaction.
