### ISSUE TITLE
Instructions for Rackspace Cloud Newbie

### ISSUE THREAD

**Issue by nathanbrauer** [chmouel/ftp-cloudfs#30]
Hello -

I found this project via a blog post which promises it can be used to access RS Cloud Files via FTP (and use nautilus on Ubuntu to access it).
http://blog.chmouel.com/2011/04/06/uploading-to-rackspace-cloud-files-via-ftp/

I've installed everything w/ no errors, but I don't know what to do from here.  I'm familiar with Ubuntu (I live on it) and FTP.  I'm only familiar with RS Cloud Files to the point where I log in to manage.rackspacecloud.com, click "Cloud Files", create a container, and upload files.  I don't do any programmatic management (we're only using it to store archived files right now).

So, what's this issue for?  It's a request to write a step-by-step "Getting started" as part of the README for how to get started after installation with a common FTP program like FileZilla or nautilus.

A million thanks!

**Comment by reidrac** [comment]
It's a good idea!

May be we can add a "QUICKSTART" page to the wiki: https://github.com/chmouel/ftp-cloudfs/wiki

**Comment by nathanbrauer** [comment]
That works!  Then, just link to it from the README.

**Comment by reidrac** [comment]
OK, finally I wrote a quick start guide:

https://github.com/chmouel/ftp-cloudfs/wiki/QuickStart

Please let me know if it works for you!
