### ISSUE TITLE
Shared dict for max connection from the same IP not being updated correctly

### ISSUE THREAD

**Issue by reidrac** [chmouel/ftp-cloudfs#36]
How to reproduce it:
1. Configuration:

```
[ftpcloudfs]
workers = 2
max-cons-per-ip = 1
memcache = 127.0.0.1:1121
```
1. Command line:

```
bin/ftpcloudfs -a https://auth.storage.memset.com/v1.0 --syslog -v
```

This is the resulting log of opening two connections with telnet:

```
Sep 12 14:20:44 juan ftpcloudfs[6665]: Serving FTP on 127.0.0.1:2021
Sep 12 14:20:44 juan ftpcloudfs[6655]: Serving FTP on 127.0.0.1:2021
Sep 12 14:20:44 juan ftpcloudfs[6666]: Serving FTP on 127.0.0.1:2021
Sep 12 14:20:50 juan ftpcloudfs[6655]: []127.0.0.1:44340 Connected.
Sep 12 14:20:50 juan ftpcloudfs[6655]: 127.0.0.1:44340 Connected, shared ip map: {'127.0.0.1': 1}
Sep 12 14:20:50 juan ftpcloudfs[6655]: 127.0.0.1:44340 Connection track: 127.0.0.1 -> 1
Sep 12 14:20:50 juan ftpcloudfs[6655]: 127.0.0.1:44340 ==> 220 Rackspace Cloud Files 0.17.1 using pyftpdlib 0.6.0 ready.
Sep 12 14:20:52 juan ftpcloudfs[6655]: []127.0.0.1:44341 Connected.
Sep 12 14:20:52 juan ftpcloudfs[6655]: 127.0.0.1:44341 ==> 421 Too many connections from the same IP address.
Sep 12 14:20:52 juan ftpcloudfs[6655]: []@127.0.0.1:44341 Too many connections from the same IP address.
Sep 12 14:20:52 juan ftpcloudfs[6655]: 127.0.0.1:44341 Disconnected, shared ip map: {}
Sep 12 14:20:52 juan ftpcloudfs[6655]: []@127.0.0.1:44341 Disconnected.
```

Looks like the shared dictionary is not being properly updated. After the second connection gets rejected the shared dict should contain '127.0.0.1' with 1.

This comes from #35

**Comment by sirkonst** [comment]
I know why shared_ip_map is clean.

Because when FTPServer, but not MyFTPHandler (!!!),  detected "max connection form ip", he call close(). But close() called from MyFTPHandler which clears shared_ip_map.

Therefore I moved processing max_cons_per_ip to MyFTPHandler. Maybe you know a better way...

**Comment by reidrac** [comment]
I see the problem now. So the pyftpdlib implementation of max_cons_per_ip is interfering with our shared dict implementation.

Sometimes it works, and it could be explained because when a different worker deals with the second connection there's no interference from FTPServer.

OK, I think the right fix would be disabling FTPServer support for max_cons_per_ip when using the shared dict and using it otherwise (ie. one worker).

Let me give it ago!

**Comment by reidrac** [comment]
Well, actually we can basically stop using the FTPServer support :)

**Comment by reidrac** [comment]
I'm running the tests and I'm going to commit something that, at the end, it's just your original change.

Sorry about that!

**Comment by reidrac** [comment]
It's fixed in d3b8e1a0ad9d19c27ccd2852f58103c8ac47f534.

Thanks again for your patch!

**Comment by reidrac** [comment]
Btw, Can I have your mail address so I can add you to the contributors list?

**Comment by sirkonst** [comment]
Yes, I do not mind. I'm interested in the development of project.
