### ISSUE TITLE
100% CPU

### ISSUE THREAD

**Issue by sirkonst** [chmouel/ftp-cloudfs#37]
Quite often I see 100% CPU usage a worker(s) but in log I don't see any active. I don't know how to reproduce it, but it's a real problem.

If I attaching to the problem worker by strace, I see lot of very frequent calls select():

```
...
select(22, [8 9 10 11 12 13 14 21], [8 9 10 11 12 13 14], [8 9 10 11 12 13 14 21], {1, 0}) = 14 (in [8 9 10 11 12 13 14], out [8 9 10 11 12 13 14], left {0, 999997})
select(22, [8 9 10 11 12 13 14 21], [8 9 10 11 12 13 14], [8 9 10 11 12 13 14 21], {1, 0}) = 14 (in [8 9 10 11 12 13 14], out [8 9 10 11 12 13 14], left {0, 999997})
select(22, [8 9 10 11 12 13 14 21], [8 9 10 11 12 13 14], [8 9 10 11 12 13 14 21], {1, 0}) = 14 (in [8 9 10 11 12 13 14], out [8 9 10 11 12 13 14], left {0, 999997})
select(22, [8 9 10 11 12 13 14 21], [8 9 10 11 12 13 14], [8 9 10 11 12 13 14 21], {1, 0}) = 14 (in [8 9 10 11 12 13 14], out [8 9 10 11 12 13 14], left {0, 999997})
select(22, [8 9 10 11 12 13 14 21], [8 9 10 11 12 13 14], [8 9 10 11 12 13 14 21], {1, 0}) = 14 (in [8 9 10 11 12 13 14], out [8 9 10 11 12 13 14], left {0, 999997})
select(22, [8 9 10 11 12 13 14 21], [8 9 10 11 12 13 14], [8 9 10 11 12 13 14 21], {1, 0}^C <unfinished ...>
```

**Comment by reidrac** [comment]
I can't reproduce it, I haven't seen that behaviour in any of our deployments.

The select timeout it's 1 second, that is the default of pyftpdlib. In your tests, is the select call waiting for 1 second?

We can change that in serve_forever call and increase the timeout... but I'm not sure if that's the real problem.

Another thing you could try is use_poll flag of serve_forever so it uses poll instead of select, but I'd like to know what's going on first!

**Comment by reidrac** [comment]
Any news on this?

**Comment by sirkonst** [comment]
Unfortunately, I very often see it in my deployments.

From strace I see what select() calling more then one per second, about 100 per second or more. But log is silent.

I tried change to use use_poll, but it did not help...

**Comment by reidrac** [comment]
It shouldn't be less than 1 second (that's select's timeout). I'll try to investigate further, although I can't reproduce it,

**Comment by reidrac** [comment]
Any new findings on this?

**Comment by sirkonst** [comment]
No... I dislike how ftp-cloudfs loads CPU, but so far, I just put up with this.

**Comment by reidrac** [comment]
OK, please reopen the bug if you found anything we can test!
