### ISSUE TITLE
Large object support

### ISSUE THREAD

**Issue by NuxRo** [chmouel/ftp-cloudfs#38]
Hello,

Does ftp-cloudfs support large object (as in splitting it in segments smaller than the defined max size)?
The max size of an object is something that's plaguing swift right now in my view.

**Comment by reidrac** [comment]
No, it doesn't support uploads. Currently it depends on the limit that it's set in the cluster (5GB by default).

For downloads there's no problem, you can download the manifest file and all the parts are merged on the fly. The only limitation so far is that manifest files return 0 bytes size in object listings and there's no way we know is a manifest file (so we can make an extra API call to get the real size, thus the sum of all the parts).

The problem with uploads is that there's no convention on how do we store the parts (size, name or location). When I need to store big files I'm using FILENAME for manifest and FILENAME.part/{0000, n} for the parts, but that could be implemented in a total different way.

If you want to support uploads, patches are welcome; although we need to address the problem of not getting the right size of the manifest, and that's something we need to fix in Swift.

**Comment by NuxRo** [comment]
Hi,

Unfortunately I not a coder, though it looks like I might need to become one, a lot of stuff needs work. :-)
Can't you take some inspiration from the swift cli tool and the way it splits the file? I'm thinking the same logic could be used for ftp-cloudfs? Or am I really wrong?
