### ISSUE TITLE
Implement REST + RETR support

### ISSUE THREAD

**Issue by reidrac** [chmouel/ftp-cloudfs#39]
Currently REST support doesn't work and it would be nice specially for continuing interrupted transfers of big files.
#### CloudFilesDS.seek is not implemented

~~We could delay the endheaders call in prepare_chunk until the first chunk is sent so we can add a range request header if seek is called before we start the transfer. Besides we can reset the transfer if a seek is performed.~~

~~I that way I think implementing seek would be feasible.~~

(the chunked object is used in write operations)

We must add a Range header to the GET request.

Refs:
- https://github.com/chmouel/ftp-cloudfs/blob/master/ftpcloudfs/chunkobject.py#L35
- https://github.com/chmouel/ftp-cloudfs/blob/master/ftpcloudfs/fs.py#L163
#### Manifest files' size is wrong, makes REST impossible (FTP error 554)

Support for large objects using a manifest file has some limitations, being the most relevant than the real size of the file (the sum of all the parts) is expensive to calculate.

Because of that the reported file size in a container listing will be 0 any seek request will fail because the offeset will be bigger than the file size (error 554).

We can potentially modify listdir_conatiner to perform an extra request for 0 bytes files with MD5 not matching an empty file to get the real size. Then we can store that file size in the cache.

Refs: https://github.com/chmouel/ftp-cloudfs/blob/master/ftpcloudfs/fs.py#L227

Comments & suggestions are welcome!

**Comment by sirkonst** [comment]
+1 :-)

**Comment by sirkonst** [comment]
Checking for manifect files not only for 0 bytes, also Content-Type must be not application/directory.

**Comment by reidrac** [comment]
Yes, good point, although then the MD5 will match the MD5 of a empty file.

In the case of a manifest file the MD5 field is based on the MD5 of all the parts, so I believe that the 0 length + MD5 different than d41d8cd98f00b204e9800998ecf8427e makes sense.

**Comment by reidrac** [comment]
It's not as easy as I thought because the MD5 of a manifest file as returned by list_objects_info is actually "d41d8cd98f00b204e9800998ecf8427e" :(

The problem is that we may have zero size files that are not a manifest, so potentially we can make some unneeded API calls to check files that are not manifest files at all.

But well, at least we can skip directories checking that "application/directory" content-type and we have a cache, so I'm going to implement that!

**Comment by reidrac** [comment]
Done!

Changes:
- sha: 253cab765668e4745bfd075f62defa277a7f1d2c
- sha: c889280270142077cfffe68901dda4cb416a827b

Please test!

**Comment by sirkonst** [comment]
Great! I'll check on this week.

**Comment by sirkonst** [comment]
I tested by FileZilla. Segment's files work fine, but when I try RETR downloading always start at first... How can I test RETR any?

**Comment by reidrac** [comment]
It doesn't work that way.

It's unrelated to segmented files. Try any large file, download 10%. Stop. Download again and when filezilla asks if it should replace the file... just say resume. Your download should continue from 10% :)

**Comment by sirkonst** [comment]
Hmm, I think it is bug filezilla, I tried resume download by wget and all OK.

Thanks, it is good features! :-)

**Comment by reidrac** [comment]
Oh, btw... in order to work it needs to be a binary file (that's a Filezilla restriction, no related to the FTP service). Filezilla uses an extension list, it might be the issue!

Try with mp3 extension or something like that.
