### ISSUE TITLE
Support files bigger than 5 GB

### ISSUE THREAD

**Issue by ncw** [chmouel/ftp-cloudfs#44]
At the moment files bigger than 5 GB get uploaded then fail when they pass 5GB with a 413 error from the proxy.

Suggested plan for uploads
- make a `split_size` parameter (say) default to 1 GB (say)
- If the upload passes the `split_size` then
- close the current upload on the proxy
- server side copy it to a new directory to be the first part `0001`
- truncate the original path to 0 length
- set `X-Object-Manifest` on the original path to point to the parts directory
- carry on receiving data into part `0002` then `0003` etc

This allows us to receive small files as we do at the moment without making them multi-part but fall back to making bigger parts.  The copy process, though server side, can be expensive though so might want to do that in the background while receiving the other parts.

Downloads should work fine, except for possibly their length which might need a bit of tweaking.

[See large objects docs here](http://docs.openstack.org/developer/swift/overview_large_objects.html)

**Comment by reidrac** [comment]
Issue migrated to: https://github.com/cloudfs/ftp-cloudfs/issues/1
