### ISSUE TITLE
Ubuntu 12.04 install: another way, another issues.

### ISSUE THREAD

**Issue by ReifiedException** [chmouel/ftp-cloudfs#46]
This time I have tried to install ftp-cloudfs in a way suggested for Debian/Ubuntu installation:

apt-get -y install python-daemon python-stdeb
pypi-install python-memcached
pypi-install python-cloudfiles
pypi-install pyftpdlib
pypi-install ftp-cloudfs

Looks like the last package installation procedure makes its checking against the wrong packages name:

dpkg: dependency problems prevent configuration of python-ftp-cloudfs:
 python-ftp-cloudfs depends on python-memcache; however:
  Package python-memcache is not installed.

(I am not python user, so it's just a wild guess)

**Comment by reidrac** [comment]
Debian changes the name of the package adding a "python" prefix, so it's not the same that is used by PyPI. If you want to install packages with Debian tools, you have to change setup.py (adding the prefix).

I know is very convenient to install Debian packages, but setup.py has to support PyPi (and only PyPi).
