### ISSUE TITLE
Migrate to pyrax

### ISSUE THREAD

**Issue by robertjpayne** [chmouel/ftp-cloudfs#47]
cloudfiles has been deprecated and pyrax is the new standard for connecting to cloud files.

**Comment by reidrac** [comment]
I was thinking about going with python-swiftclient because is object storage specific, but it's in the roadmap indeed. We need to deal with pyftpdlib upgrade first, but thanks for reporting this.

**Comment by robertjpayne** [comment]
pyrax uses python-swiftclient under the hood so it actually may be better to just skip the middleman as pyrax is very much for Rackspace ( though can be bent to will ).

**Comment by chmouel** [comment]
pyrax is just a wrapper to bunch of openstack clients libs (including swiftclient) so we should def use swiftclient directly as ftpcloudfs don't have RAX specifics stuff anymore (except maybe servicenet).

**Comment by reidrac** [comment]
Good stuff! +1 swiftclient.

As I said I want to tackle issue #45, but I didn't have the time to fight all the unicode changes introduced by pyftpdlib 1.0.x. After that, migrating to swiftclient shouldn't be that difficult.

We can think about changing the name of the project as we move towards openstack support and less cloud files specific (we already did that adding auth 2.0 support).

**Comment by chmouel** [comment]
+2 to it as well and we could at the same time move it its own git repo or even better to somethign like stackforge

**Comment by reidrac** [comment]
Bump!

I'm going to release 0.21 with pyftpdlib 1.2 support and I think it will be the last version supporting python-cloudfiles.

After that I'll start porting to python-swiftclient.

**Comment by reidrac** [comment]
Done!

I've ported ftp-cloudfs to python-swiftclient, there's a release candidate branch at:

https://github.com/chmouel/ftp-cloudfs/tree/swiftclient

I plan to release it in a couple of days once I'm done with testing, and then I'll close this ticket!

**Comment by reidrac** [comment]
0.23 is out!
