### ISSUE TITLE
Can't start ftp-cloudfs via script

### ISSUE THREAD

**Issue by mikeduk** [chmouel/ftp-cloudfs#48]
I'm having problems getting  ftpcloudfs to run via any script file on Ubuntu 12.04 that I don't manually run myself.

If I put the following line in one of my startup scripts I can see the the script is running but ftpcloudfs does not start for some reason:

ftpcloudfs -v -b 0.0.0.0 --log-file=/tmp/cloudfs.log

I have also tried checking for the process in a cron job and if it is not running then starting it but that also has the same effect. There are no entries in the log file specified or in any system log that I can see.

What is the recommended method of starting the service each time the system boots?

Thanks

**Comment by reidrac** [comment]
Take a look to our QuickStart:

https://github.com/chmouel/ftp-cloudfs/wiki/QuickStart

There are different ways to start a process every time the system boots, but first make it run manually to be sure there aren't errors. I recommend you to follow the QuickStart step by step.

After that you can search for Ubuntu specific info about how to start a service on boot.

Tip: take a look to the init script used by the Debian package: http://anonscm.debian.org/gitweb/?p=openstack/ftp-cloudfs.git;a=blob;f=debian/ftp-cloudfs.init.d;h=658d60fd07d799e25f95f39cd3dbf39bacacff61;hb=HEAD
