### ISSUE TITLE
What Type of Mode ftp-cloudfs supports(Active/Passive)? Need quick help on this. Can any one please suggest?

### ISSUE THREAD

**Issue by Lguvvala** [chmouel/ftp-cloudfs#52]
Would like to know what type of mode ftp-cloudfs supports. We are looking for Active mode connection, but found it is not working as expected. Any one could you please help me out in this regard asap.

**Comment by reidrac** [comment]
Supports both, depends on your network setup.

The project has moved to: https://github.com/cloudfs/ftp-cloudfs

**Comment by Lguvvala** [comment]
Thanks for your help. Is there any way to open the connection in active mode or by default it opens connection in active mode? Your help is very much appreciated. Thank You.

**Comment by Lguvvala** [comment]
@reidrac Found that you closed this issue, but am looking for more info. Could you please provide me or point me to the documentation where it have all these details?

**Comment by reidrac** [comment]
You're opening a ticket in the wrong place.

As I said it support both modes by default. It is a server, the passive or active mode is negotiated by the client.

If you want to know more about the ftp support, check https://github.com/giampaolo/pyftpdlib that is the library that is used for the ftp layer.

**Comment by Lguvvala** [comment]
@reidrac Thanks for your suggestion. Could you please suggest me where to open new ticket to sort out our problem?
