### ISSUE TITLE
Licence confusion

### ISSUE THREAD

**Issue by reidrac** [chmouel/ftp-cloudfs#7]
README.rst is confusing about the project licence:
- At the beginning states that the project is BSD licensed
- At the end the licence is MIT

The setup.py says both MIT and BSD again.

Besides that it would be a good idea to include the license at the beginning of all source files.

I would provide a patch, but I think the licensing part must be done by the copyright holder(s) (just in case I got something wrong).

**Comment by chmouel** [comment]
Humm I tought MIT is a BSD type license or maybe not, I am happy to standardize over BSD if that's the most liberated license and accept a patch that clean-up all of it....

**Comment by reidrac** [comment]
I think the effect of both licenses is almost the same, but the license text is different and actually are different licenses (I'm not a lawyer, so I can't be more specific).

In fact you did the right thing including the license text in the README.rst file. That's the thing that counts, the fact you say is a MIT or whatever license it's just informative.

Clearing this point will help the project it's included in Linux distributions that care about the legal stuff.

Thanks!

**Comment by reidrac** [comment]
Uh, that reference should a github bug or I did something by accident. It's not related to this issue.

I'll send you a cleaning patch ASAP.

**Comment by reidrac** [comment]
Made a pull request, closing this issue.
